---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nynasunner/public_html/
    - /bin/cp -R _data $DEPLOYPATH
    - /bin/cp -R _includes $DEPLOYPATH
    - /bin/cp -R _layouts $DEPLOYPATH
    - /bin/cp -R _microblog $DEPLOYPATH
    - /bin/cp -R _plugins $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R misc $DEPLOYPATH
    - /bin/cp -R _config.yml $DEPLOYPATH
    - /bin/cp -R 404.md $DEPLOYPATH
    - /bin/cp -R about.md $DEPLOYPATH
    - /bin/cp -R gem.bak $DEPLOYPATH
    - /bin/cp -R Gemfile $DEPLOYPATH
    - /bin/cp -R Gemfile.lock $DEPLOYPATH
    - /bin/cp -R index.md $DEPLOYPATH
    - /bin/cp -R links.md $DEPLOYPATH
    - /bin/cp -R microblog.md $DEPLOYPATH
    - /bin/cp -R posts.md $DEPLOYPATH
    - /bin/cp -R tags.md $DEPLOYPATH